version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka-server:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CREATE_TOPICS: "bidding_results:1:1" # " Topic Name : Partition : Replication factor "

  redis-server:
    image: "redis:latest"
    ports:
      - 6379:6379

  ssp-server:
    build: ./ssp-server
    container_name: ssp-server
    depends_on:
      - kafka-server
      - redis-server
    ports:
      - "3000:3000"

  consumer1:
    build: ./consumer1
    container_name: consumer1
    depends_on:
      - kafka-server

  consumer2:
    build: ./consumer2
    container_name: consumer2
    depends_on:
      - kafka-server

  dsp-server:
    build: ./dsp-server
    container_name: dsp-server
    ports:
      - "3001:3001"

  client:
    build: ./client
    container_name: client
    ports:
      - "8080:8080"
